### PR TITLE
Add additional accessibilty

### PR DESCRIPTION
**Pull request by GavHern**
Makes GDBrowser more accessible to people who have motor or visionary impairments.

- [x] Gives many formerly inaccessible buttons tab indices so they can be accessed through keyboard navigation. Triggers a click event when the user presses <kbd>Enter</kbd> while focused on them
- [x] Disables CSS transitions and animations for people who have reduced motion enabled in their system settings. Also disables them for very low-performance browsers that may be slowed down by transitions.

This can still be built on but is just a very basic implementation to make the website more useable with the keyboard. For better accessibility, the markup could be rearranged where necessary, so tabbing through items is more predictable. I've rearranged some things on the home page for that reason but I've left other pages as is.

Additionally, `tabindex` attributes are added to inaccessible via javascript, but would be more efficient by adding them to each element in the markup directly. I didn't want to intrude too much on the project, I just wanted it to be a little more usable with the keyboard.

### CODE REVIEW

**Comment by GDColon** [comment]
Whoaa this looks super promising, thank you so much! I'll look through the fork a little bit later

**Comment by GDColon** [comment]
Alright I looked through it, it works really nicely! Obviously it's not perfect but still helpful nonetheless. My only suggestion before merging is that instead of making a new .js file for accessibility you could just add it to sizecheck.js (probably going to rename the file anyways since I use it for all global scripts now).

**Comment by GavHern** [comment]
oh alright, I can do that a little bit later.

lmk if there's anything else UI/UX related that you might need someone to work on!

**Comment by GDColon** [comment]
Looks good! I might try to expand on this in the future

**Pull request merged**
