### PR TITLE
Code formatting and semantics

### PR DESCRIPTION
**Pull request by 101arrowz**
Here's some edits I've made with code formatting done by [Prettier](https://prettier.io) and some minor functional changes, for example moving to `express.static` rather than manually using `fs`. I don't have the `secretStuff.json` thing so I'm not sure if it works properly completely. Based on my testing, however, it works fine.

If you're OK with merging my changes, please clone the repo, verify that everything works, and if something doesn't reply to this PR or make changes.

### CODE REVIEW

**Comment by 101arrowz** [comment]
I've done some more testing and no, it doesn't work. Closing until I fix it.

**Comment by 101arrowz** [comment]
Fixed bugs with latest commit. Now everything is working :)

**Comment by GDColon** [comment]
While some of the changes are pretty good, there's a couple I'm not so sure about. I'm most likely not going to merge, but I'll still find time to implement a few of the changes I like.

Also, secretStuff.json just has ID and GJP

**Comment by 101arrowz** [comment]
Could you elaborate on what you didn't like from the PR?

If nothing else, please consider moving all `require` statements outside of the exported functions. It will DRAMATICALLY improve performance. Also, keeping the secret in a special file is probably a good idea.

**Pull request closed without merging**
