### PR TITLE
fixed a bug with GDPS

### PR DESCRIPTION
**Pull request by WOSHIZHAZHA120**
@GDColon

### CODE REVIEW

**Comment by 101arrowz** [comment]
Did you test it to verify it works? My suggestion was more of an idea, not necessarily the answer.

**Comment by GDColon** [comment]
Report back on if it works, and also please remove the commenting below the parameters.

**Comment by WOSHIZHAZHA120** [comment]
Sorry, i tested now, song is normal but demon didn't have difficulty, always extreme demon.

**Comment by 101arrowz** [comment]
Please either send me the URL to the GDPS or log the body at [this line](https://github.com/GDColon/GDBrowser/blob/master/api/level.js#L25) and post the result here. (Just write `console.log(body);`)

**Comment by WOSHIZHAZHA120** [comment]
> Please either send me the URL to the GDPS or log the body at [this line](https://github.com/GDColon/GDBrowser/blob/master/api/level.js#L25) and post the result here. (Just write `console.log(body);`)

I don't know where is node.js output

so I send the data to getGJLevel21.php and post

these is return:

1: 1344: 2: LoL: 5: 5: 6: 74: 8: 10: 9: 50: 10: 216: 12: 0: 13: 21: 14: 48: 17: 0: 43: 0: 25: 1: 18: 0: 19: 0: 42: 0: 45: 306: 3: aXR6IGEgYXV0byBsZXZlbC4gZG8gbm90IHRvdWNoIGFueXRoaW5nIDop: 15: 2: 30: 0: 31: 0: 37: 0: 38: 0: 39: 1: 46: 1: 47: 2: 40: 0: 35: 5000253#74: ItzRainbowdash: 16#1~|~5000253~|~2~|~buttercup~|~3~|~9~|~4~|~JackStauber~|~5~|~3.17~|~6~|~~|~10~|~http%3A%2F%2Fmusic.163.com%2Fsong%2Fmedia%2Fouter%2Furl%3Fid%3D1353428173.mp3~|~7~|~~|~8~|~0#1: 0: 10#24dc570c0ccf38efd80b595ceea02bc28b86fe10

**Comment by GDColon** [comment]
The level appears as auto on my end, so the problem is likely with your own code. If the rating was demon, you would see "17:1" in the response.

Maybe update to a clean new fork of GDBrowser?

image

**Pull request closed without merging**
