### PR TITLE
Replaced cookies with localStorage and added custom dragscroll

### PR DESCRIPTION
**Pull request by 101arrowz**
Cookies can, of course, be used to hold data. However, the `localStorage` API is much more friendly to developers. I've made a few incredibly minor changes that allow us to remove the `cookie-parser` dependency while maintaining easier-to-read code than the cookies used before.

Literally the entire `localStorage` API (that we need to care about) is `setItem(key, value)`, `removeItem(key)`, and `getItem(key)`. This makes life a LOT easier compared to cookie parsing.

I also fixed the `Buffer.from` accident to still use a non-deprecated method but it actually works now :P. Sorry about that bad commit!

Also, I'm really sorry about all the extraneous commits being added to my PRs! I'm not very good at GitHub myself, I think it's because I'm using the same local repo without recloning but I'm not sure :(

### CODE REVIEW

**Comment by GDColon** [comment]
Looking at the code, I may have spotted a few issues. But I'll download the changes later and see if everything works fine.

**Comment by 101arrowz** [comment]
I added a custom dragscroll! It's laggy as heck but now you have your beloved text detection.

**Comment by GDColon** [comment]
AMAZING WORK!!!! (as always)
Although I did come across a small little bug - tough to explain but here goes
1) Go to a comment page
2) Click and hold on someone's username, drag away, and release (so you don't go to their account)
3) Your cursor is now in 'dragscroll' mode despite not actually pressing the mouse

(finally, I can't seem to select any text. although that may just be the CSS)

**Comment by 101arrowz** [comment]
Hm. I'll have to look into that. I programmed a `mouseleave` event specifically to handle that case. I'll try to fix it.

As for the comments not being selected, yes that's the CSS. simply remove the `user-select: none` in the `.comments` of the `browser.css` to fix.

Will make another commit in an hour or two to fix comment bug.

**Comment by GDColon** [comment]
Sounds great! I'll update the CSS after school and then merge.

**Comment by GDColon** [comment]
Added! (not merged bc i changed some stuff)

**Pull request closed without merging**
