### PR TITLE
Better error handling + general cleanup

### PR DESCRIPTION
**Pull request by punctuations**
I stumbled across this and wanted to do some ~~spring~~ winter cleaning :)
Please let me know if there is anything else that could be done as cleanup and or if I have messed something up!

Additions:
+ added to .gitignore file
+ added better error handling with status codes on all requests
+ refused connections that require POST method with status code 405 (Method not allowed)
+ added dev command to package.json

Deletions:
- cleaned up the .gitignore file, removing /typings and /.next, the project does not use both next.js and typescript.
- removed unused parameters in api/post and api/messages
- removed an odd space in the server.json file

Question:
- one question, however, why are the response messages all 0, -1, -2, -3? I understand that it is what RobTop does but there are definitely ways to go about it that provide more feedback than a cryptic integer.
- Is this still being actively maintained/added to or is this just sitting in the background and getting updates only when required?

### CODE REVIEW

**Comment by GDColon** [comment]
Oh this is awesome!!! I appreciate the contribution a lot.
The site is still somewhat maintained but a lot of code is really messy since I started this project a long time ago.

My thoughts
- I very much admit that the error handling sucks balls. I mostly just wanted a quick way to check if the response is valid, so I resorted to using RobTop's method of returning -1. I started this project with little webdev experience and part of me feels like changing the current system would take too long to fix and ultimately isn't worth it.
- Express sends 200 as the default status code, I'd personally avoid cluttering up the code with .status(200) and would rather make other status codes stand out more
- I don't think returning 'method not allowed' is worth it, pretty sure those files can only ever run from post requests anyways
- -2 is returned for accurate leaderboard because private servers don't use it. Unlike -1, -2 removes the accurate button on the frontend. Boomlings leaderboard I just don't see a reason to have this work on private servers lol

**Comment by punctuations** [comment]
That's fair; however, returning 200 on those things are more just there to clear up (considering the response is just usually integers) confusion of what is and isn't a success, and for method not allowed, it is nice just in case, I personally don't use express in a ton of my projects so I don't even know if they are or are not accessible but if someone does happen to make a request that isn't a post request (this goes for /messages too) then it will return an error code that is able to accurately describe the situation, it can be removed if you wanted but I just wanted to clear that up, at the end of the day it is your project!

**Comment by punctuations** [comment]
And for private servers do you want the status code updated from 418 (I'm a teapot) or not? I will make a commit to remove the comments around that and clarify to anyone in the future with a new comment on what it does.

**Comment by punctuations** [comment]
and the last thing, this is totally just a suggestion, if you do get a lot of people checking this out still it may be worthwhile to make an issue and pin it just to convert all the images in /assets to .webp to decrease loading times :)

**Comment by punctuations** [comment]
bump

**Comment by GDColon** [comment]
Will get to this eventually, just busy with other things

**Comment by GDColon** [comment]
Alright hi again, so everything here looks good and I'm willing to merge this, though you'll have to revisit a few spots since there might be conflicts from the recent icon update. Thanks again for doing this!

**Comment by punctuations** [comment]
> Alright hi again, so everything here looks good and I'm willing to merge this, though you'll have to revisit a few spots since there might be conflicts from the recent icon update. Thanks again for doing this!

Conflicts have been fixed!

**Comment by GDColon** [comment]
Please don't merge the two icon code files

**Comment by punctuations** [comment]
do you mean the two in the API Route?

**Comment by sudocode1** [comment]
the codeql security checks related to rate limiting can be ignored because in production a rate limit is enabled, its just not enabled by default (from what i can see), the cross site scripting ones are likely of concern though

**Comment by GDColon** [comment]
this has nothing to do with the failed checks, that's on my end for being a bad programmer
but yeah just don't merge icon.js and icon_old.js, i split them up for a reason

**Comment by sudocode1** [comment]
ah ok my bad, didnt realise

**Comment by punctuations** [comment]
is this what you were looking for in regards to icon.js and icon_old.js?

I've just reverted them prior to 84d02b7, all other files from that commit are the same.

as a summary:
- icon_old.js has been deleted, as it did not exist prior to commit 84d02b7
- icon.js' state is that of the contents prior to commit 84d02b7

**Comment by GDColon** [comment]
ok what now i'm just confused.
please look at [this recent commit](https://github.com/GDColon/GDBrowser/commit/84d02b7271f64f630a29c6062b396b70e810a106), it's what i was referring to

**Comment by punctuations** [comment]
I am as well, you asked me to not merge the icon and icon_old files

**Comment by GDColon** [comment]
Tell you what just leave both icon and icon_old untouched, everyting else is cool and good

**Comment by GDColon** [comment]
Aite I'm gonna merge now then properly clean things up in the next commit I'm about to push, ty for the help!

**Pull request merged**
