### PR TITLE
Added custom connectTimeout; add credential encryption (not yet functional)

### PR DESCRIPTION
**Pull request by 101arrowz**
Yikes, it's been a while since I've worked on this project.

I implemented a custom `connect-timeout` middleware. I don't have time to explain what I did/how to utilize the new features right now, will edit this PR later. For now it's plug-n-play and doesn't log to console or send a weird default response.

EDIT: Here's a summary:

You do `app.use(timeout(ms, res))` to wait `ms` (a number) milliseconds before responding with `res` or, if it is a function, responding with its return value. In any route, you can do `res.timeout = ms` to update the timeout to `ms` for that specific route. `res.onTimeout` is called when timeout occurs, and its return value (if there is one) is sent to the client. The default response is `{"err": "timeout"}`.

### CODE REVIEW

**Comment by GDColon** [comment]
nice

**Comment by GDUcrash** [comment]
nice

**Comment by 101arrowz** [comment]
haha it's the sex number ecks dee

**Comment by 101arrowz** [comment]
Basically fixed the middleware and added the boilerplate for credential encryption. You can delete after you merge if you don't want it, it's completely disabled right now but would save the encrypted password on client side in the future.

**Comment by Altenhh** [comment]
nice

**Comment by Qufyy** [comment]
nice

**Comment by GDUcrash** [comment]
This is all nice and stuff but @GDColon can you finally merge this?! Also, nice

**Comment by 101arrowz** [comment]
There's no need to rush, the project is stable and this PR isn't that important. However, merging before too many more commits would be a good idea to avoid nasty merge conflicts.

**Comment by iProgramMC** [comment]
You should add some kind of branch check or else errors may appear in your final repo, like with AppVeyor.

**Comment by 101arrowz** [comment]
I'm not sure a CI is something that we can integrate at this point. We don't even have tests yet. Also Colon doesn't seem to like making major changes (I couldn't get flexbox added or jQuery removed, I've already tried).

**Comment by 101arrowz** [comment]
@GDColon Any plans to review this at some point?

**Comment by GDColon** [comment]
aggggg ill try to push myself to do it

**Comment by Flux3on** [comment]
@GDColon Soon™?

**Comment by Flux3on** [comment]
Happy 11 day anniversary of that comment! 😆

**Comment by 101arrowz** [comment]
@GDColon

**Comment by GDColon** [comment]
I tried it out, it just says `{ "err": "timeout" }` no matter what.

Honestly after a lot of thinking/demotivation I feel like the current timeout is fine since I don't need a custom timeout response for GDBrowser. But if you wanna publish this PR as a standalone node module it would be really awesome for future projects and I would gladly use it.

**Pull request closed without merging**
