### PR TITLE
Improved Page Load/TTI

### PR DESCRIPTION
**Pull request by 101arrowz**
These commits drastically improve page load, aka time to interactive (TTI), via a variety of techniques.

All images were compressed to a lossy format using [pngquant](https://pngquant.org), but they still look identical to the originals. This change saves as much as 60% data of the images.

I switched all jQuery script tags to use the minifed version. I'm not sure if it was intentional not to use the minified build (AFAIK there's literally no benefit besides code readability, which isn't important for users). However, this saves about 150 kB per page.

I added in the `compression` NPM module to automagically serve gzipped data when possible. gzip is a compression technique that can reduce bundles by up to 70% in addition to all the previous savings.

On my machine the pages are significantly faster to load. I hope these changes help!

P.S. I'm not sure why the first and last commits are there, but they are and there's nothing I can do about it :/ Also, I forgot to mention that I removed the `font` tags, which are illegal in the HTML5 spec and only work in Chrome, Firefox, etc. because some browsers try to correct for mistakes by developers.

### CODE REVIEW

**Comment by GDColon** [comment]
Intersting, as always. I'll have a look at the changes tomorrow and tell you what I think. Thank you so much for continuing to help me out, despite my meanness ;)

**Comment by 101arrowz** [comment]
I'm not sure what you mean by "meanness" (you've been very nice to me) but I'm always happy to work on an open source project!

Also, thank you so much for adding me to the credits! It really does mean a lot to me. I realize that I may be selfish in asking this, but I'd love if you'd create individual panes for major GitHub contributors such as myself, since I've made multiple major, functional changes to the codebase and will likely add more in the coming weeks.

I'm sorry if that came off as rude or demanding, and if you don't think I've helped as much as the others with individual panes, I'm regardless very grateful for the credit currently given on the page!

Looking forward to seeing your feedback on the PR!

**Comment by GDColon** [comment]
The main reason I didn't put you on a full page is because you said you don't have much social media, so consistency between the social media buttons at the bottom would be difficult. 
Anyways, I'm off to bed - will look through the PR tomorrow. (in the meantime, it might be a good idea to make the code work with the update I just pushed)

**Comment by 101arrowz** [comment]
I've made the necessary merge. Everything works as expected!

I didn't want to give socials because I don't really use them, but if you need them to put me on athe contributors page:

YouTube: https://www.youtube.com/channel/UCuloR4qLkF3QGw8WUHjcNuQ
Twitter: https://twitter.com/@arjunbarrett
Discord: 101arrowz#7108 (prefer this over Twitter on contributors but if it's too hard it doesn't matter)

I'm okay with giving these publicly since again, I literally don't use them.
You told me you wanted no functional changes on frontend, but if you want me to make it possible to have any number of socials and/or make the site not have a minimum height to width ratio, let me know :)

**Comment by GDColon** [comment]
You never fail to impress me, my friend. Merged 😃 
(also, what's the new middleware compressing exactly?)

**Pull request merged**
