### PR TITLE
Add easter egg

### PR DESCRIPTION
**Pull request by etstringy**
Inputting the Konami code on the main page (up up down down left right left right b a), will now cause a box to pop up saying "you found an easter egg" and will play the Main Menu loop Megalovania remix by Mudstep (showcased in your video titled **I Beta Tested Geometry Dash 2.2 [April Fools**])

image

### CODE REVIEW

**Comment by etstringy** [comment]
Okay, i've just seen this, but i don't know how my previous pull requests commit got in here..
(Changed urls for Saved and HoF levels to be more consistant with othe…)

**Comment by ItzSwirlz** [comment]
This is fire

**Comment by GDColon** [comment]
Funny idea, but I don't see a reason to add this.

**Comment by ItzSwirlz** [comment]
bruh ever heard of fun? I was thinking maybe adding vaults in gdbrowser ngl

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
